### ISSUE TITLE
Index out of range issue

### ISSUE THREAD

**Issue by jaikishantulswani** [redhuntlabs/HTTPLoot#1]
Hi @0xInfection Thank you for this tool. I am having issues while running this with multiple hosts as it throws `Index out of range` even with a valid list of hosts.

```
 runtime error: index out of range [1] with length 1

goroutine 672 [running]:
main.findSecrets({0xc0000d0060, 0x18}, {0xc00039e6f0, 0x2a}, 0xc000330090)
	/home/infected/Work/rhl/gitlab/httl/loot.go:24 +0x2d8
main.getJavascript({{0xc0000d0000, 0x5}, {0x0, 0x0}, 0x0, {0xc0000d0008, 0x10}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/home/infected/Work/rhl/gitlab/httl/loot.go:51 +0x233
created by main.(*ProcJob).ExecuteCrawler.func2
	/home/infected/Work/rhl/gitlab/httl/process.go:109 +0x532

```

**Comment by orkosec** [comment]
I was struggling with this too.
line 25 of loot.go it is using index number 1 but the length of that slice would be 1.
changing string(y[1]) to string(y[0]) fixed it.

`log.Printf("Secrets found -> Type: %s | Secret: %s", typerex, string(y[0]))`
`writer.Write([]string{typerex + " Exposed", origPath, secPath, string(y[0])})`

**Comment by jaikishantulswani** [comment]
@kasraorko Thank you, it is fixed now :)

**Comment by 0xInfection** [comment]
Thanks for reporting the issue @jaikishantulswani and for the PR @kasraorko!
