### ISSUE TITLE
required files not specified in README

### ISSUE THREAD

**Issue by j75** [redhuntlabs/HTTPLoot#6]
Hello,

I think this phrase form the README should be modified:
> to use the tool, you can grab any one of the pre-built binaries from the Releases  section of the repository

You also need to have in the same folder the files **lootdb.json** and **regexes.json**.
Running the application also creates a "hidden" folder **.colly_cache**.

**Comment by 0xInfection** [comment]
Hey @j75!

Thanks for your comments. I think you are correct, a mention in the README file would be great. Doing it now. :)

Cheers!

**Comment by 0xInfection** [comment]
Done! Fixed in: ef2585d.
